blank_issues_enabled: false
contact_links:
  - name: Suporte ou sugestões externas
    url: https://github.com/Eman134/evolva-core/discussions
    about: Use o espaço de discussões para tópicos não técnicos.
